package com.spark.psi.order.storage.sales;

import com.jiuqi.dna.core.def.table.TableDeclarator;
import com.jiuqi.dna.core.type.TypeFactory;
import com.jiuqi.dna.core.def.table.TableFieldDefine;
import com.jiuqi.dna.core.def.table.TableFieldDeclare;
import com.jiuqi.dna.core.def.exp.ConstExpression;

public final class TB_SA_SALES_RETURN extends TableDeclarator {

	public static final String TABLE_NAME ="SA_SALES_RETURN";

	public final TableFieldDefine f_tenantsId;
	public final TableFieldDefine f_creatorId;
	public final TableFieldDefine f_creator;
	public final TableFieldDefine f_createDate;
	public final TableFieldDefine f_orderNumber;
	public final TableFieldDefine f_partnerId;
	public final TableFieldDefine f_partnerShortName;
	public final TableFieldDefine f_partnerName;
	public final TableFieldDefine f_partnerNamePY;
	public final TableFieldDefine f_partnerFax;
	public final TableFieldDefine f_contactId;
	public final TableFieldDefine f_contactName;
	public final TableFieldDefine f_contactTel;
	public final TableFieldDefine f_contactPhone;
	public final TableFieldDefine f_returnCause;
	public final TableFieldDefine f_remark;
	public final TableFieldDefine f_totalAmount;
	public final TableFieldDefine f_type;
	public final TableFieldDefine f_state;
	public final TableFieldDefine f_deptId;
	public final TableFieldDefine f_isStoped;
	public final TableFieldDefine f_examin;
	public final TableFieldDefine f_effectiveDate;
	public final TableFieldDefine f_deliveryDate;
	public final TableFieldDefine f_defOne;
	public final TableFieldDefine f_defTwo;
	public final TableFieldDefine f_defThree;
	public final TableFieldDefine f_defFour;
	public final TableFieldDefine f_defFive;
	public final TableFieldDefine f_defSix;
	public final TableFieldDefine f_defSeven;
	public final TableFieldDefine f_defEight;
	public final TableFieldDefine f_defNine;
	public final TableFieldDefine f_defTen;

	public static final String FN_tenantsId ="tenantsId";
	public static final String FN_creatorId ="creatorId";
	public static final String FN_creator ="creator";
	public static final String FN_createDate ="createDate";
	public static final String FN_orderNumber ="orderNumber";
	public static final String FN_partnerId ="partnerId";
	public static final String FN_partnerShortName ="partnerShortName";
	public static final String FN_partnerName ="partnerName";
	public static final String FN_partnerNamePY ="partnerNamePY";
	public static final String FN_partnerFax ="partnerFax";
	public static final String FN_contactId ="contactId";
	public static final String FN_contactName ="contactName";
	public static final String FN_contactTel ="contactTel";
	public static final String FN_contactPhone ="contactPhone";
	public static final String FN_returnCause ="returnCause";
	public static final String FN_remark ="remark";
	public static final String FN_totalAmount ="totalAmount";
	public static final String FN_type ="type";
	public static final String FN_state ="state";
	public static final String FN_deptId ="deptId";
	public static final String FN_isStoped ="isStoped";
	public static final String FN_examin ="examin";
	public static final String FN_effectiveDate ="effectiveDate";
	public static final String FN_deliveryDate ="deliveryDate";
	public static final String FN_defOne ="defOne";
	public static final String FN_defTwo ="defTwo";
	public static final String FN_defThree ="defThree";
	public static final String FN_defFour ="defFour";
	public static final String FN_defFive ="defFive";
	public static final String FN_defSix ="defSix";
	public static final String FN_defSeven ="defSeven";
	public static final String FN_defEight ="defEight";
	public static final String FN_defNine ="defNine";
	public static final String FN_defTen ="defTen";

	//不可调用该构造方法.当前类只能由框架实例化.
	private TB_SA_SALES_RETURN() {
		super(TABLE_NAME);
		this.table.setTitle("销售退货信息表");
		TableFieldDeclare field;
		this.f_tenantsId = field = this.table.newField(FN_tenantsId, TypeFactory.GUID);
		field.setTitle("租户GUID");
		this.f_creatorId = field = this.table.newField(FN_creatorId, TypeFactory.GUID);
		field.setTitle("创建人GUID");
		this.f_creator = field = this.table.newField(FN_creator, TypeFactory.VARCHAR(50));
		field.setTitle("创建人姓名");
		this.f_createDate = field = this.table.newField(FN_createDate, TypeFactory.DATE);
		field.setTitle("创建日期");
		this.f_orderNumber = field = this.table.newField(FN_orderNumber, TypeFactory.NVARCHAR(20));
		field.setTitle("销售订单编号");
		this.f_partnerId = field = this.table.newField(FN_partnerId, TypeFactory.GUID);
		field.setTitle("客户GUID");
		this.f_partnerShortName = field = this.table.newField(FN_partnerShortName, TypeFactory.NVARCHAR(20));
		field.setTitle("客户名称");
		this.f_partnerName = field = this.table.newField(FN_partnerName, TypeFactory.NVARCHAR(100));
		field.setTitle("客户全称");
		this.f_partnerNamePY = field = this.table.newField(FN_partnerNamePY, TypeFactory.NVARCHAR(50));
		field.setTitle("客户拼音");
		this.f_partnerFax = field = this.table.newField(FN_partnerFax, TypeFactory.NVARCHAR(20));
		field.setTitle("客户传真");
		this.f_contactId = field = this.table.newField(FN_contactId, TypeFactory.GUID);
		field.setTitle("联系人GUID");
		this.f_contactName = field = this.table.newField(FN_contactName, TypeFactory.NVARCHAR(40));
		field.setTitle("联系人");
		this.f_contactTel = field = this.table.newField(FN_contactTel, TypeFactory.NVARCHAR(20));
		field.setTitle("联系人电话");
		this.f_contactPhone = field = this.table.newField(FN_contactPhone, TypeFactory.NVARCHAR(20));
		field.setTitle("联系人手机");
		this.f_returnCause = field = this.table.newField(FN_returnCause, TypeFactory.NVARCHAR(200));
		field.setTitle("退回/中止原因");
		this.f_remark = field = this.table.newField(FN_remark, TypeFactory.NVARCHAR(1000));
		field.setTitle("备注");
		this.f_totalAmount = field = this.table.newField(FN_totalAmount, TypeFactory.NUMERIC(17,2));
		field.setTitle("总金额");
		field.setDefault(ConstExpression.builder.expOf(0.0));
		this.f_type = field = this.table.newField(FN_type, TypeFactory.CHAR(2));
		field.setTitle("类型");
		this.f_state = field = this.table.newField(FN_state, TypeFactory.CHAR(2));
		field.setTitle("处理情况");
		this.f_deptId = field = this.table.newField(FN_deptId, TypeFactory.GUID);
		field.setTitle("所属部门部门GUID");
		this.f_isStoped = field = this.table.newField(FN_isStoped, TypeFactory.BOOLEAN);
		field.setTitle("是否中止状态");
		this.f_examin = field = this.table.newField(FN_examin, TypeFactory.NVARCHAR(1000));
		field.setTitle("审核人及日期");
		this.f_effectiveDate = field = this.table.newField(FN_effectiveDate, TypeFactory.DATE);
		field.setTitle("订单生效时间");
		this.f_deliveryDate = field = this.table.newField(FN_deliveryDate, TypeFactory.DATE);
		field.setTitle("交货日期");
		this.f_defOne = field = this.table.newField(FN_defOne, TypeFactory.NVARCHAR(100));
		field.setTitle("用户自定义字段1");
		this.f_defTwo = field = this.table.newField(FN_defTwo, TypeFactory.NVARCHAR(100));
		field.setTitle("用户自定义字段2");
		this.f_defThree = field = this.table.newField(FN_defThree, TypeFactory.NVARCHAR(100));
		field.setTitle("用户自定义字段3");
		this.f_defFour = field = this.table.newField(FN_defFour, TypeFactory.NUMERIC(17,2));
		field.setTitle("用户自定义字段4");
		this.f_defFive = field = this.table.newField(FN_defFive, TypeFactory.NUMERIC(17,2));
		field.setTitle("用户自定义字段5");
		this.f_defSix = field = this.table.newField(FN_defSix, TypeFactory.NUMERIC(17,2));
		field.setTitle("用户自定义字段6");
		this.f_defSeven = field = this.table.newField(FN_defSeven, TypeFactory.DATE);
		field.setTitle("用户自定义字段7");
		this.f_defEight = field = this.table.newField(FN_defEight, TypeFactory.DATE);
		field.setTitle("用户自定义字段8");
		this.f_defNine = field = this.table.newField(FN_defNine, TypeFactory.CHAR(2));
		field.setTitle("用户自定义字段9");
		this.f_defTen = field = this.table.newField(FN_defTen, TypeFactory.CHAR(2));
		field.setTitle("用户自定义字段10");
	}

}
