package com.spark.psi.storage.account.receipt;

import com.jiuqi.dna.core.def.table.TableDeclarator;
import com.jiuqi.dna.core.type.TypeFactory;
import com.jiuqi.dna.core.def.table.TableFieldDefine;
import com.jiuqi.dna.core.def.table.TableFieldDeclare;
import com.jiuqi.dna.core.def.exp.ConstExpression;

public final class TB_SA_FINANCE_RECEIPT_RECORD extends TableDeclarator {

	public static final String TABLE_NAME ="SA_FINANCE_RECEIPT_RECORD";

	public final TableFieldDefine f_receiptBillNo;
	public final TableFieldDefine f_tenantsGuid;
	public final TableFieldDefine f_receiptDate;
	public final TableFieldDefine f_receiptObjectGuid;
	public final TableFieldDefine f_receiptObject;
	public final TableFieldDefine f_receiptObjectShort;
	public final TableFieldDefine f_receiptType;
	public final TableFieldDefine f_receiptTypeName;
	public final TableFieldDefine f_receiptWay;
	public final TableFieldDefine f_receiptWayName;
	public final TableFieldDefine f_receiptMoney;
	public final TableFieldDefine f_receiverGuid;
	public final TableFieldDefine f_receiver;
	public final TableFieldDefine f_affirmPerson;
	public final TableFieldDefine f_affirmDate;
	public final TableFieldDefine f_remark;
	public final TableFieldDefine f_deptGuid;
	public final TableFieldDefine f_saleEmpGuid;
	public final TableFieldDefine f_saleEmpName;
	public final TableFieldDefine f_shouldCardCount;
	public final TableFieldDefine f_shouldCardMoney;
	public final TableFieldDefine f_retailGuid;
	public final TableFieldDefine f_receiptObjectPY;
	public final TableFieldDefine f_receiptObjectShortPY;
	public final TableFieldDefine f_receiptTypeNamePY;
	public final TableFieldDefine f_receiptWayNamePY;
	public final TableFieldDefine f_receiverPY;
	public final TableFieldDefine f_affirmPersonPY;
	public final TableFieldDefine f_isRetail;
	public final TableFieldDefine f_isSureReceipt;
	public final TableFieldDefine f_saleEmpNamePY;
	public final TableFieldDefine f_isRetailDataByPay;
	public final TableFieldDefine f_quarter;
	public final TableFieldDefine f_remonth;

	public static final String FN_receiptBillNo ="receiptBillNo";
	public static final String FN_tenantsGuid ="tenantsGuid";
	public static final String FN_receiptDate ="receiptDate";
	public static final String FN_receiptObjectGuid ="receiptObjectGuid";
	public static final String FN_receiptObject ="receiptObject";
	public static final String FN_receiptObjectShort ="receiptObjectShort";
	public static final String FN_receiptType ="receiptType";
	public static final String FN_receiptTypeName ="receiptTypeName";
	public static final String FN_receiptWay ="receiptWay";
	public static final String FN_receiptWayName ="receiptWayName";
	public static final String FN_receiptMoney ="receiptMoney";
	public static final String FN_receiverGuid ="receiverGuid";
	public static final String FN_receiver ="receiver";
	public static final String FN_affirmPerson ="affirmPerson";
	public static final String FN_affirmDate ="affirmDate";
	public static final String FN_remark ="remark";
	public static final String FN_deptGuid ="deptGuid";
	public static final String FN_saleEmpGuid ="saleEmpGuid";
	public static final String FN_saleEmpName ="saleEmpName";
	public static final String FN_shouldCardCount ="shouldCardCount";
	public static final String FN_shouldCardMoney ="shouldCardMoney";
	public static final String FN_retailGuid ="retailGuid";
	public static final String FN_receiptObjectPY ="receiptObjectPY";
	public static final String FN_receiptObjectShortPY ="receiptObjectShortPY";
	public static final String FN_receiptTypeNamePY ="receiptTypeNamePY";
	public static final String FN_receiptWayNamePY ="receiptWayNamePY";
	public static final String FN_receiverPY ="receiverPY";
	public static final String FN_affirmPersonPY ="affirmPersonPY";
	public static final String FN_isRetail ="isRetail";
	public static final String FN_isSureReceipt ="isSureReceipt";
	public static final String FN_saleEmpNamePY ="saleEmpNamePY";
	public static final String FN_isRetailDataByPay ="isRetailDataByPay";
	public static final String FN_quarter ="quarter";
	public static final String FN_remonth ="remonth";

	//不可调用该构造方法.当前类只能由框架实例化.
	private TB_SA_FINANCE_RECEIPT_RECORD() {
		super(TABLE_NAME);
		this.table.setDescription("收款纪录信息表");
		this.table.setTitle("收款纪录信息表");
		this.table.setCategory("业务主体");
		TableFieldDeclare field;
		this.f_receiptBillNo = field = this.table.newField(FN_receiptBillNo, TypeFactory.NVARCHAR(20));
		field.setTitle("收款单编号");
		this.f_tenantsGuid = field = this.table.newField(FN_tenantsGuid, TypeFactory.GUID);
		field.setTitle("租户编号");
		this.f_receiptDate = field = this.table.newField(FN_receiptDate, TypeFactory.DATE);
		field.setTitle("收款日期");
		this.f_receiptObjectGuid = field = this.table.newField(FN_receiptObjectGuid, TypeFactory.GUID);
		field.setTitle("收款对象编号");
		this.f_receiptObject = field = this.table.newField(FN_receiptObject, TypeFactory.NVARCHAR(20));
		field.setTitle("收款对象名称");
		this.f_receiptObjectShort = field = this.table.newField(FN_receiptObjectShort, TypeFactory.NVARCHAR(20));
		field.setTitle("收款对象简称");
		this.f_receiptType = field = this.table.newField(FN_receiptType, TypeFactory.CHAR(2));
		field.setTitle("收款类型");
		this.f_receiptTypeName = field = this.table.newField(FN_receiptTypeName, TypeFactory.NVARCHAR(10));
		field.setTitle("收款类型名称");
		this.f_receiptWay = field = this.table.newField(FN_receiptWay, TypeFactory.CHAR(2));
		field.setTitle("收款方式");
		this.f_receiptWayName = field = this.table.newField(FN_receiptWayName, TypeFactory.NVARCHAR(10));
		field.setTitle("收款方式名称");
		this.f_receiptMoney = field = this.table.newField(FN_receiptMoney, TypeFactory.NUMERIC(17,2));
		field.setTitle("收款金额");
		this.f_receiverGuid = field = this.table.newField(FN_receiverGuid, TypeFactory.GUID);
		field.setTitle("收款人编号");
		this.f_receiver = field = this.table.newField(FN_receiver, TypeFactory.NVARCHAR(20));
		field.setTitle("收款人");
		this.f_affirmPerson = field = this.table.newField(FN_affirmPerson, TypeFactory.NVARCHAR(20));
		field.setTitle("确认人");
		this.f_affirmDate = field = this.table.newField(FN_affirmDate, TypeFactory.DATE);
		field.setTitle("确认日期");
		this.f_remark = field = this.table.newField(FN_remark, TypeFactory.NVARCHAR(1000));
		field.setTitle("备注");
		this.f_deptGuid = field = this.table.newField(FN_deptGuid, TypeFactory.GUID);
		field.setTitle("部门编号");
		this.f_saleEmpGuid = field = this.table.newField(FN_saleEmpGuid, TypeFactory.GUID);
		field.setTitle("销售员工编号");
		this.f_saleEmpName = field = this.table.newField(FN_saleEmpName, TypeFactory.NVARCHAR(20));
		field.setTitle("销售员工名称");
		this.f_shouldCardCount = field = this.table.newField(FN_shouldCardCount, TypeFactory.INT);
		field.setTitle("应交刷卡底单（数量）");
		this.f_shouldCardMoney = field = this.table.newField(FN_shouldCardMoney, TypeFactory.NUMERIC(17,2));
		field.setTitle("应交刷卡底单（金额）");
		this.f_retailGuid = field = this.table.newField(FN_retailGuid, TypeFactory.GUID);
		field.setTitle("零售单据编号");
		this.f_receiptObjectPY = field = this.table.newField(FN_receiptObjectPY, TypeFactory.NVARCHAR(20));
		field.setTitle("收款对象名称拼音");
		this.f_receiptObjectShortPY = field = this.table.newField(FN_receiptObjectShortPY, TypeFactory.NVARCHAR(20));
		field.setTitle("收款对象简称拼音");
		this.f_receiptTypeNamePY = field = this.table.newField(FN_receiptTypeNamePY, TypeFactory.NVARCHAR(10));
		field.setTitle("收款类型名称拼音");
		this.f_receiptWayNamePY = field = this.table.newField(FN_receiptWayNamePY, TypeFactory.NVARCHAR(10));
		field.setTitle("收款方式名称拼音");
		this.f_receiverPY = field = this.table.newField(FN_receiverPY, TypeFactory.NVARCHAR(20));
		field.setTitle("收款人拼音");
		this.f_affirmPersonPY = field = this.table.newField(FN_affirmPersonPY, TypeFactory.NVARCHAR(20));
		field.setTitle("确认人拼音");
		this.f_isRetail = field = this.table.newField(FN_isRetail, TypeFactory.BOOLEAN);
		field.setTitle("是否零售");
		this.f_isSureReceipt = field = this.table.newField(FN_isSureReceipt, TypeFactory.BOOLEAN);
		field.setTitle("是否确认收款");
		this.f_saleEmpNamePY = field = this.table.newField(FN_saleEmpNamePY, TypeFactory.NVARCHAR(10));
		field.setTitle("销售员工名称拼音");
		this.f_isRetailDataByPay = field = this.table.newField(FN_isRetailDataByPay, TypeFactory.BOOLEAN);
		field.setTitle("是否零售退款数据(付款)");
		field.setDefault(ConstExpression.builder.expOf(false));
		this.f_quarter = field = this.table.newField(FN_quarter, TypeFactory.INT);
		field.setTitle("季度");
		this.f_remonth = field = this.table.newField(FN_remonth, TypeFactory.INT);
		field.setTitle("月份");
		this.table.newIndex("IDX_RECEIPT_RECORD",f_tenantsGuid);
	}

}
