package com.spark.psi.order.storage;

import com.jiuqi.dna.core.ObjectQuerier;
import com.jiuqi.dna.core.def.arg.ArgumentDefine;
import com.jiuqi.dna.core.def.query.QueryColumnDefine;
import com.jiuqi.dna.core.def.query.QueryStatementDeclarator;

public final class sadsds extends QueryStatementDeclarator {


		public final ArgumentDefine arg_tenantsGuid;
		public final ArgumentDefine arg_cusPGuid;
		public final ArgumentDefine arg_createGuid;
		public final ArgumentDefine arg_submitstatus;
		public final ArgumentDefine arg_rebutstatus;
		public final ArgumentDefine arg_examstatus;
		public final ArgumentDefine arg_noStoreStatus;
		public final ArgumentDefine arg_partStoreStatus;
		public final ArgumentDefine arg_allStoreStatus;
		public final ArgumentDefine arg_noConsignment;
		public final ArgumentDefine arg_yesConsignment;

		public final QueryColumnDefine c_recid;
		public final QueryColumnDefine c_tenantsGuid;
		public final QueryColumnDefine c_billsNo;
		public final QueryColumnDefine c_cuspGuid;
		public final QueryColumnDefine c_cuspName;
		public final QueryColumnDefine c_cuspFullName;
		public final QueryColumnDefine c_cuspFullNamePY;
		public final QueryColumnDefine c_cuspFax;
		public final QueryColumnDefine c_consigneeGuid;
		public final QueryColumnDefine c_consignee;
		public final QueryColumnDefine c_consigneeTel;
		public final QueryColumnDefine c_linkmanGuid;
		public final QueryColumnDefine c_linkman;
		public final QueryColumnDefine c_linkmanTel;
		public final QueryColumnDefine c_address;
		public final QueryColumnDefine c_rebutCause;
		public final QueryColumnDefine c_stopCause;
		public final QueryColumnDefine c_remark;
		public final QueryColumnDefine c_totalAmount;
		public final QueryColumnDefine c_type;
		public final QueryColumnDefine c_createGuid;
		public final QueryColumnDefine c_createPerson;
		public final QueryColumnDefine c_createDate;
		public final QueryColumnDefine c_status;
		public final QueryColumnDefine c_isStoped;
		public final QueryColumnDefine c_examin;
		public final QueryColumnDefine c_goodsTotalCount;
		public final QueryColumnDefine c_goodsOkCount;
		public final QueryColumnDefine c_defOne;
		public final QueryColumnDefine c_defTwo;
		public final QueryColumnDefine c_defThree;
		public final QueryColumnDefine c_defFour;
		public final QueryColumnDefine c_defFive;
		public final QueryColumnDefine c_defSix;
		public final QueryColumnDefine c_defSeven;
		public final QueryColumnDefine c_defEight;
		public final QueryColumnDefine c_defNine;
		public final QueryColumnDefine c_defTen;
		public final QueryColumnDefine c_payDate;
		public final QueryColumnDefine c_deptGuid;

		public sadsds() {
			this.arg_tenantsGuid = this.query.getArguments().get(0);
			this.arg_cusPGuid = this.query.getArguments().get(1);
			this.arg_createGuid = this.query.getArguments().get(2);
			this.arg_submitstatus = this.query.getArguments().get(3);
			this.arg_rebutstatus = this.query.getArguments().get(4);
			this.arg_examstatus = this.query.getArguments().get(5);
			this.arg_noStoreStatus = this.query.getArguments().get(6);
			this.arg_partStoreStatus = this.query.getArguments().get(7);
			this.arg_allStoreStatus = this.query.getArguments().get(8);
			this.arg_noConsignment = this.query.getArguments().get(9);
			this.arg_yesConsignment = this.query.getArguments().get(10);
			this.c_recid = this.query.getColumns().get(0);
			this.c_tenantsGuid = this.query.getColumns().get(1);
			this.c_billsNo = this.query.getColumns().get(2);
			this.c_cuspGuid = this.query.getColumns().get(3);
			this.c_cuspName = this.query.getColumns().get(4);
			this.c_cuspFullName = this.query.getColumns().get(5);
			this.c_cuspFullNamePY = this.query.getColumns().get(6);
			this.c_cuspFax = this.query.getColumns().get(7);
			this.c_consigneeGuid = this.query.getColumns().get(8);
			this.c_consignee = this.query.getColumns().get(9);
			this.c_consigneeTel = this.query.getColumns().get(10);
			this.c_linkmanGuid = this.query.getColumns().get(11);
			this.c_linkman = this.query.getColumns().get(12);
			this.c_linkmanTel = this.query.getColumns().get(13);
			this.c_address = this.query.getColumns().get(14);
			this.c_rebutCause = this.query.getColumns().get(15);
			this.c_stopCause = this.query.getColumns().get(16);
			this.c_remark = this.query.getColumns().get(17);
			this.c_totalAmount = this.query.getColumns().get(18);
			this.c_type = this.query.getColumns().get(19);
			this.c_createGuid = this.query.getColumns().get(20);
			this.c_createPerson = this.query.getColumns().get(21);
			this.c_createDate = this.query.getColumns().get(22);
			this.c_status = this.query.getColumns().get(23);
			this.c_isStoped = this.query.getColumns().get(24);
			this.c_examin = this.query.getColumns().get(25);
			this.c_goodsTotalCount = this.query.getColumns().get(26);
			this.c_goodsOkCount = this.query.getColumns().get(27);
			this.c_defOne = this.query.getColumns().get(28);
			this.c_defTwo = this.query.getColumns().get(29);
			this.c_defThree = this.query.getColumns().get(30);
			this.c_defFour = this.query.getColumns().get(31);
			this.c_defFive = this.query.getColumns().get(32);
			this.c_defSix = this.query.getColumns().get(33);
			this.c_defSeven = this.query.getColumns().get(34);
			this.c_defEight = this.query.getColumns().get(35);
			this.c_defNine = this.query.getColumns().get(36);
			this.c_defTen = this.query.getColumns().get(37);
			this.c_payDate = this.query.getColumns().get(38);
			this.c_deptGuid = this.query.getColumns().get(39);
		}
	}
