package com.spark.psi.storage.base.material;

import com.jiuqi.dna.core.def.table.TableDeclarator;
import com.jiuqi.dna.core.type.TypeFactory;
import com.jiuqi.dna.core.def.table.TableFieldDefine;
import com.jiuqi.dna.core.def.table.TableFieldDeclare;

public final class TB_PSI_Base_MaterialItem extends TableDeclarator {

	public static final String TABLE_NAME ="PSI_Base_MaterialItem";

	public final TableFieldDefine f_materialCode;
	public final TableFieldDefine f_materialNo;
	public final TableFieldDefine f_materialName;
	public final TableFieldDefine f_namePY;
	public final TableFieldDefine f_categoryId;
	public final TableFieldDefine f_spec;
	public final TableFieldDefine f_scale;
	public final TableFieldDefine f_inventoryStrategy;
	public final TableFieldDefine f_materialUnit;
	public final TableFieldDefine f_avgBuyPrice;
	public final TableFieldDefine f_totalStoreUpper;
	public final TableFieldDefine f_totalStoreFlore;
	public final TableFieldDefine f_totalStoreAmount;
	public final TableFieldDefine f_shelfLife;
	public final TableFieldDefine f_warningDay;
	public final TableFieldDefine f_salePrice;
	public final TableFieldDefine f_standardPrice;
	public final TableFieldDefine f_planPrice;
	public final TableFieldDefine f_status;
	public final TableFieldDefine f_remark;
	public final TableFieldDefine f_canDelete;
	public final TableFieldDefine f_refFlag;
	public final TableFieldDefine f_createDate;
	public final TableFieldDefine f_lastModifyDate;
	public final TableFieldDefine f_lastModifyPerson;
	public final TableFieldDefine f_warningType;
	public final TableFieldDefine f_materialProperties;
	public final TableFieldDefine f_creatorId;
	public final TableFieldDefine f_creator;
	public final TableFieldDefine f_materialId;
	public final TableFieldDefine f_lossRate;
	public final TableFieldDefine f_recentPurchasePrice;

	public static final String FN_materialCode ="materialCode";
	public static final String FN_materialNo ="materialNo";
	public static final String FN_materialName ="materialName";
	public static final String FN_namePY ="namePY";
	public static final String FN_categoryId ="categoryId";
	public static final String FN_spec ="spec";
	public static final String FN_scale ="scale";
	public static final String FN_inventoryStrategy ="inventoryStrategy";
	public static final String FN_materialUnit ="materialUnit";
	public static final String FN_avgBuyPrice ="avgBuyPrice";
	public static final String FN_totalStoreUpper ="totalStoreUpper";
	public static final String FN_totalStoreFlore ="totalStoreFlore";
	public static final String FN_totalStoreAmount ="totalStoreAmount";
	public static final String FN_shelfLife ="shelfLife";
	public static final String FN_warningDay ="warningDay";
	public static final String FN_salePrice ="salePrice";
	public static final String FN_standardPrice ="standardPrice";
	public static final String FN_planPrice ="planPrice";
	public static final String FN_status ="status";
	public static final String FN_remark ="remark";
	public static final String FN_canDelete ="canDelete";
	public static final String FN_refFlag ="refFlag";
	public static final String FN_createDate ="createDate";
	public static final String FN_lastModifyDate ="lastModifyDate";
	public static final String FN_lastModifyPerson ="lastModifyPerson";
	public static final String FN_warningType ="warningType";
	public static final String FN_materialProperties ="materialProperties";
	public static final String FN_creatorId ="creatorId";
	public static final String FN_creator ="creator";
	public static final String FN_materialId ="materialId";
	public static final String FN_lossRate ="lossRate";
	public static final String FN_recentPurchasePrice ="recentPurchasePrice";

	//不可调用该构造方法.当前类只能由框架实例化.
	private TB_PSI_Base_MaterialItem() {
		super(TABLE_NAME);
		this.table.setTitle("材料条目");
		this.table.setCategory("基础数据主体");
		TableFieldDeclare field;
		this.f_materialCode = field = this.table.newField(FN_materialCode, TypeFactory.NVARCHAR(30));
		field.setTitle("商品编码");
		this.f_materialNo = field = this.table.newField(FN_materialNo, TypeFactory.NVARCHAR(30));
		field.setTitle("商品条码");
		this.f_materialName = field = this.table.newField(FN_materialName, TypeFactory.NVARCHAR(100));
		field.setTitle("商品名称");
		this.f_namePY = field = this.table.newField(FN_namePY, TypeFactory.NVARCHAR(100));
		field.setTitle("拼音");
		this.f_categoryId = field = this.table.newField(FN_categoryId, TypeFactory.GUID);
		field.setTitle("商品分类GUID");
		this.f_spec = field = this.table.newField(FN_spec, TypeFactory.NVARCHAR(50));
		field.setTitle("规格");
		this.f_scale = field = this.table.newField(FN_scale, TypeFactory.INT);
		field.setTitle("精度");
		this.f_inventoryStrategy = field = this.table.newField(FN_inventoryStrategy, TypeFactory.CHAR(2));
		field.setTitle("库存策略");
		this.f_materialUnit = field = this.table.newField(FN_materialUnit, TypeFactory.NVARCHAR(40));
		field.setTitle("商品单位");
		this.f_avgBuyPrice = field = this.table.newField(FN_avgBuyPrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("平均采购价格");
		this.f_totalStoreUpper = field = this.table.newField(FN_totalStoreUpper, TypeFactory.NUMERIC(17,5));
		field.setTitle("总库存上限数量");
		this.f_totalStoreFlore = field = this.table.newField(FN_totalStoreFlore, TypeFactory.NUMERIC(17,5));
		field.setTitle("总库存下限数量");
		this.f_totalStoreAmount = field = this.table.newField(FN_totalStoreAmount, TypeFactory.NUMERIC(17,2));
		field.setTitle("总库存上限金额");
		this.f_shelfLife = field = this.table.newField(FN_shelfLife, TypeFactory.INT);
		field.setTitle("保质期");
		this.f_warningDay = field = this.table.newField(FN_warningDay, TypeFactory.INT);
		field.setTitle("预警天数");
		this.f_salePrice = field = this.table.newField(FN_salePrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("销售价格");
		this.f_standardPrice = field = this.table.newField(FN_standardPrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("标准价格");
		this.f_planPrice = field = this.table.newField(FN_planPrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("计划价格");
		this.f_status = field = this.table.newField(FN_status, TypeFactory.CHAR(2));
		field.setTitle("商品状态");
		this.f_remark = field = this.table.newField(FN_remark, TypeFactory.NVARCHAR(1000));
		field.setTitle("备注");
		this.f_canDelete = field = this.table.newField(FN_canDelete, TypeFactory.BOOLEAN);
		field.setTitle("是否可以删除");
		this.f_refFlag = field = this.table.newField(FN_refFlag, TypeFactory.BOOLEAN);
		field.setTitle("关联标识");
		this.f_createDate = field = this.table.newField(FN_createDate, TypeFactory.DATE);
		field.setTitle("数据插入时间");
		this.f_lastModifyDate = field = this.table.newField(FN_lastModifyDate, TypeFactory.DATE);
		field.setTitle("数据最后修改时间");
		this.f_lastModifyPerson = field = this.table.newField(FN_lastModifyPerson, TypeFactory.NVARCHAR(10));
		field.setTitle("数据最后修改人");
		this.f_warningType = field = this.table.newField(FN_warningType, TypeFactory.CHAR(2));
		field.setTitle("商品预警类型");
		this.f_materialProperties = field = this.table.newField(FN_materialProperties, TypeFactory.NVARCHAR(1000));
		field.setTitle("分类属性值");
		this.f_creatorId = field = this.table.newField(FN_creatorId, TypeFactory.GUID);
		field.setTitle("创建人Guid");
		this.f_creator = field = this.table.newField(FN_creator, TypeFactory.NVARCHAR(30));
		field.setTitle("创建人");
		this.f_materialId = field = this.table.newField(FN_materialId, TypeFactory.GUID);
		field.setTitle("材料ID");
		this.f_lossRate = field = this.table.newField(FN_lossRate, TypeFactory.NUMERIC(17,2));
		field.setTitle("损耗率");
		this.f_recentPurchasePrice = field = this.table.newField(FN_recentPurchasePrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("最近采购价格");
	}

}
