package com.spark.cms.storage.extra;

import com.jiuqi.dna.core.def.table.TableDeclarator;
import com.jiuqi.dna.core.type.TypeFactory;
import com.jiuqi.dna.core.def.table.TableFieldDefine;
import com.jiuqi.dna.core.def.table.TableFieldDeclare;

public final class TB_cms_question extends TableDeclarator {

	public static final String TABLE_NAME ="cms_question";

	public final TableFieldDefine f_question1;
	public final TableFieldDefine f_question2;
	public final TableFieldDefine f_question3;
	public final TableFieldDefine f_question401;
	public final TableFieldDefine f_question402;
	public final TableFieldDefine f_question403;
	public final TableFieldDefine f_question404;
	public final TableFieldDefine f_question405;
	public final TableFieldDefine f_question406;
	public final TableFieldDefine f_question407;
	public final TableFieldDefine f_question408;
	public final TableFieldDefine f_question409;
	public final TableFieldDefine f_question410;
	public final TableFieldDefine f_question411;
	public final TableFieldDefine f_question5;
	public final TableFieldDefine f_question601;
	public final TableFieldDefine f_question602;
	public final TableFieldDefine f_question603;
	public final TableFieldDefine f_question604;
	public final TableFieldDefine f_question605;
	public final TableFieldDefine f_question606;
	public final TableFieldDefine f_question607;
	public final TableFieldDefine f_question608;
	public final TableFieldDefine f_question609;
	public final TableFieldDefine f_question610;
	public final TableFieldDefine f_question611;
	public final TableFieldDefine f_question7;
	public final TableFieldDefine f_question801;
	public final TableFieldDefine f_question802;
	public final TableFieldDefine f_question803;
	public final TableFieldDefine f_question804;
	public final TableFieldDefine f_question805;
	public final TableFieldDefine f_question806;
	public final TableFieldDefine f_question807;
	public final TableFieldDefine f_question808;
	public final TableFieldDefine f_question9;
	public final TableFieldDefine f_questionCreatorId;
	public final TableFieldDefine f_questionCreator;
	public final TableFieldDefine f_questionDate;

	public static final String FN_question1 ="question1";
	public static final String FN_question2 ="question2";
	public static final String FN_question3 ="question3";
	public static final String FN_question401 ="question401";
	public static final String FN_question402 ="question402";
	public static final String FN_question403 ="question403";
	public static final String FN_question404 ="question404";
	public static final String FN_question405 ="question405";
	public static final String FN_question406 ="question406";
	public static final String FN_question407 ="question407";
	public static final String FN_question408 ="question408";
	public static final String FN_question409 ="question409";
	public static final String FN_question410 ="question410";
	public static final String FN_question411 ="question411";
	public static final String FN_question5 ="question5";
	public static final String FN_question601 ="question601";
	public static final String FN_question602 ="question602";
	public static final String FN_question603 ="question603";
	public static final String FN_question604 ="question604";
	public static final String FN_question605 ="question605";
	public static final String FN_question606 ="question606";
	public static final String FN_question607 ="question607";
	public static final String FN_question608 ="question608";
	public static final String FN_question609 ="question609";
	public static final String FN_question610 ="question610";
	public static final String FN_question611 ="question611";
	public static final String FN_question7 ="question7";
	public static final String FN_question801 ="question801";
	public static final String FN_question802 ="question802";
	public static final String FN_question803 ="question803";
	public static final String FN_question804 ="question804";
	public static final String FN_question805 ="question805";
	public static final String FN_question806 ="question806";
	public static final String FN_question807 ="question807";
	public static final String FN_question808 ="question808";
	public static final String FN_question9 ="question9";
	public static final String FN_questionCreatorId ="questionCreatorId";
	public static final String FN_questionCreator ="questionCreator";
	public static final String FN_questionDate ="questionDate";

	//不可调用该构造方法.当前类只能由框架实例化.
	private TB_cms_question() {
		super(TABLE_NAME);
		this.table.setTitle("问卷调查表");
		this.table.setCategory("业务主体");
		TableFieldDeclare field;
		this.f_question1 = field = this.table.newField(FN_question1, TypeFactory.CHAR(2));
		field.setTitle("问卷答案1");
		this.f_question2 = field = this.table.newField(FN_question2, TypeFactory.CHAR(2));
		field.setTitle("问卷答案2");
		this.f_question3 = field = this.table.newField(FN_question3, TypeFactory.CHAR(2));
		field.setTitle("问卷答案3");
		this.f_question401 = field = this.table.newField(FN_question401, TypeFactory.CHAR(2));
		field.setTitle("问卷答案401");
		this.f_question402 = field = this.table.newField(FN_question402, TypeFactory.CHAR(2));
		field.setTitle("问卷答案402");
		this.f_question403 = field = this.table.newField(FN_question403, TypeFactory.CHAR(2));
		field.setTitle("问卷答案403");
		this.f_question404 = field = this.table.newField(FN_question404, TypeFactory.CHAR(2));
		field.setTitle("问卷答案404");
		this.f_question405 = field = this.table.newField(FN_question405, TypeFactory.CHAR(2));
		field.setTitle("问卷答案405");
		this.f_question406 = field = this.table.newField(FN_question406, TypeFactory.CHAR(2));
		field.setTitle("问卷答案406");
		this.f_question407 = field = this.table.newField(FN_question407, TypeFactory.CHAR(2));
		field.setTitle("问卷答案407");
		this.f_question408 = field = this.table.newField(FN_question408, TypeFactory.CHAR(2));
		field.setTitle("问卷答案408");
		this.f_question409 = field = this.table.newField(FN_question409, TypeFactory.CHAR(2));
		field.setTitle("问卷答案409");
		this.f_question410 = field = this.table.newField(FN_question410, TypeFactory.CHAR(2));
		field.setTitle("问卷答案410");
		this.f_question411 = field = this.table.newField(FN_question411, TypeFactory.CHAR(2));
		field.setTitle("问卷答案411");
		this.f_question5 = field = this.table.newField(FN_question5, TypeFactory.CHAR(2));
		field.setTitle("问卷答案5");
		this.f_question601 = field = this.table.newField(FN_question601, TypeFactory.CHAR(2));
		field.setTitle("问卷答案601");
		this.f_question602 = field = this.table.newField(FN_question602, TypeFactory.CHAR(2));
		field.setTitle("问卷答案602");
		this.f_question603 = field = this.table.newField(FN_question603, TypeFactory.CHAR(2));
		field.setTitle("问卷答案603");
		this.f_question604 = field = this.table.newField(FN_question604, TypeFactory.CHAR(2));
		field.setTitle("问卷答案604");
		this.f_question605 = field = this.table.newField(FN_question605, TypeFactory.CHAR(2));
		field.setTitle("问卷答案605");
		this.f_question606 = field = this.table.newField(FN_question606, TypeFactory.CHAR(2));
		field.setTitle("问卷答案606");
		this.f_question607 = field = this.table.newField(FN_question607, TypeFactory.CHAR(2));
		field.setTitle("问卷答案607");
		this.f_question608 = field = this.table.newField(FN_question608, TypeFactory.CHAR(2));
		field.setTitle("问卷答案608");
		this.f_question609 = field = this.table.newField(FN_question609, TypeFactory.CHAR(2));
		field.setTitle("问卷答案609");
		this.f_question610 = field = this.table.newField(FN_question610, TypeFactory.CHAR(2));
		field.setTitle("问卷答案610");
		this.f_question611 = field = this.table.newField(FN_question611, TypeFactory.CHAR(2));
		field.setTitle("问卷答案611");
		this.f_question7 = field = this.table.newField(FN_question7, TypeFactory.CHAR(2));
		field.setTitle("问卷答案7");
		this.f_question801 = field = this.table.newField(FN_question801, TypeFactory.CHAR(2));
		field.setTitle("问卷答案801");
		this.f_question802 = field = this.table.newField(FN_question802, TypeFactory.CHAR(2));
		field.setTitle("问卷答案802");
		this.f_question803 = field = this.table.newField(FN_question803, TypeFactory.CHAR(2));
		field.setTitle("问卷答案803");
		this.f_question804 = field = this.table.newField(FN_question804, TypeFactory.CHAR(2));
		field.setTitle("问卷答案804");
		this.f_question805 = field = this.table.newField(FN_question805, TypeFactory.CHAR(2));
		field.setTitle("问卷答案805");
		this.f_question806 = field = this.table.newField(FN_question806, TypeFactory.CHAR(2));
		field.setTitle("问卷答案806");
		this.f_question807 = field = this.table.newField(FN_question807, TypeFactory.CHAR(2));
		field.setTitle("问卷答案807");
		this.f_question808 = field = this.table.newField(FN_question808, TypeFactory.CHAR(2));
		field.setTitle("问卷答案808");
		this.f_question9 = field = this.table.newField(FN_question9, TypeFactory.NVARCHAR(200));
		field.setTitle("问卷答案9");
		this.f_questionCreatorId = field = this.table.newField(FN_questionCreatorId, TypeFactory.VARCHAR(10));
		field.setTitle("问卷人ID");
		this.f_questionCreator = field = this.table.newField(FN_questionCreator, TypeFactory.VARCHAR(20));
		field.setTitle("问卷人姓名");
		this.f_questionDate = field = this.table.newField(FN_questionDate, TypeFactory.DATE);
		field.setTitle("问卷时间");
	}

}
