package com.spark.erp.storage.sales;

import com.jiuqi.dna.core.def.table.TableDeclarator;
import com.jiuqi.dna.core.type.TypeFactory;
import com.jiuqi.dna.core.def.table.TableFieldDefine;
import com.jiuqi.dna.core.def.table.TableFieldDeclare;
import com.jiuqi.dna.core.def.exp.ConstExpression;

public final class TB_ERP_Sales_OnlineOrder extends TableDeclarator {

	public static final String TABLE_NAME ="ERP_Sales_OnlineOrder";

	public final TableFieldDefine f_billsNo;
	public final TableFieldDefine f_memberId;
	public final TableFieldDefine f_realName;
	public final TableFieldDefine f_consignee;
	public final TableFieldDefine f_consigneeTel;
	public final TableFieldDefine f_address;
	public final TableFieldDefine f_deliveryeDate;
	public final TableFieldDefine f_remark;
	public final TableFieldDefine f_disAmount;
	public final TableFieldDefine f_totalAmount;
	public final TableFieldDefine f_type;
	public final TableFieldDefine f_stationId;
	public final TableFieldDefine f_stationName;
	public final TableFieldDefine f_status;
	public final TableFieldDefine f_createDate;
	public final TableFieldDefine f_consignorId;
	public final TableFieldDefine f_consignor;
	public final TableFieldDefine f_consignedDate;
	public final TableFieldDefine f_deliverPersonId;
	public final TableFieldDefine f_deliverPerson;
	public final TableFieldDefine f_deliverDate;
	public final TableFieldDefine f_arrivedConfirmId;
	public final TableFieldDefine f_arrivedConfirm;
	public final TableFieldDefine f_arrivedConfirmDate;
	public final TableFieldDefine f_verificationCode;
	public final TableFieldDefine f_noVerificationReason;
	public final TableFieldDefine f_returnFlag;
	public final TableFieldDefine f_toDoor;
	public final TableFieldDefine f_deliveryCost;
	public final TableFieldDefine f_bagsCost;
	public final TableFieldDefine f_vantages;
	public final TableFieldDefine f_vantagesCost;
	public final TableFieldDefine f_payType;
	public final TableFieldDefine f_lockedDeliveryBalance;

	public static final String FN_billsNo ="billsNo";
	public static final String FN_memberId ="memberId";
	public static final String FN_realName ="realName";
	public static final String FN_consignee ="consignee";
	public static final String FN_consigneeTel ="consigneeTel";
	public static final String FN_address ="address";
	public static final String FN_deliveryeDate ="deliveryeDate";
	public static final String FN_remark ="remark";
	public static final String FN_disAmount ="disAmount";
	public static final String FN_totalAmount ="totalAmount";
	public static final String FN_type ="type";
	public static final String FN_stationId ="stationId";
	public static final String FN_stationName ="stationName";
	public static final String FN_status ="status";
	public static final String FN_createDate ="createDate";
	public static final String FN_consignorId ="consignorId";
	public static final String FN_consignor ="consignor";
	public static final String FN_consignedDate ="consignedDate";
	public static final String FN_deliverPersonId ="deliverPersonId";
	public static final String FN_deliverPerson ="deliverPerson";
	public static final String FN_deliverDate ="deliverDate";
	public static final String FN_arrivedConfirmId ="arrivedConfirmId";
	public static final String FN_arrivedConfirm ="arrivedConfirm";
	public static final String FN_arrivedConfirmDate ="arrivedConfirmDate";
	public static final String FN_verificationCode ="verificationCode";
	public static final String FN_noVerificationReason ="noVerificationReason";
	public static final String FN_returnFlag ="returnFlag";
	public static final String FN_toDoor ="toDoor";
	public static final String FN_deliveryCost ="deliveryCost";
	public static final String FN_bagsCost ="bagsCost";
	public static final String FN_vantages ="vantages";
	public static final String FN_vantagesCost ="vantagesCost";
	public static final String FN_payType ="payType";
	public static final String FN_lockedDeliveryBalance ="lockedDeliveryBalance";

	//不可调用该构造方法.当前类只能由框架实例化.
	private TB_ERP_Sales_OnlineOrder() {
		super(TABLE_NAME);
		this.table.setTitle("网上订单");
		TableFieldDeclare field;
		this.f_billsNo = field = this.table.newField(FN_billsNo, TypeFactory.NVARCHAR(20));
		field.setTitle("订单编号");
		this.f_memberId = field = this.table.newField(FN_memberId, TypeFactory.GUID);
		field.setTitle("会员id");
		this.f_realName = field = this.table.newField(FN_realName, TypeFactory.NVARCHAR(20));
		field.setTitle("真实姓名");
		this.f_consignee = field = this.table.newField(FN_consignee, TypeFactory.NVARCHAR(40));
		field.setTitle("收货人");
		this.f_consigneeTel = field = this.table.newField(FN_consigneeTel, TypeFactory.NVARCHAR(30));
		field.setTitle("收货人电话");
		this.f_address = field = this.table.newField(FN_address, TypeFactory.NVARCHAR(200));
		field.setTitle("收货地址");
		this.f_deliveryeDate = field = this.table.newField(FN_deliveryeDate, TypeFactory.DATE);
		field.setTitle("交货日期");
		this.f_remark = field = this.table.newField(FN_remark, TypeFactory.NVARCHAR(1000));
		field.setTitle("备注");
		this.f_disAmount = field = this.table.newField(FN_disAmount, TypeFactory.NUMERIC(17,2));
		field.setTitle("整单折扣");
		this.f_totalAmount = field = this.table.newField(FN_totalAmount, TypeFactory.NUMERIC(17,2));
		field.setTitle("总金额");
		this.f_type = field = this.table.newField(FN_type, TypeFactory.CHAR(2));
		field.setTitle("类型");
		this.f_stationId = field = this.table.newField(FN_stationId, TypeFactory.GUID);
		field.setTitle("站点ID");
		this.f_stationName = field = this.table.newField(FN_stationName, TypeFactory.NVARCHAR(50));
		field.setTitle("站点名称");
		this.f_status = field = this.table.newField(FN_status, TypeFactory.CHAR(2));
		field.setTitle("状态");
		this.f_createDate = field = this.table.newField(FN_createDate, TypeFactory.DATE);
		field.setTitle("创建日期");
		this.f_consignorId = field = this.table.newField(FN_consignorId, TypeFactory.GUID);
		field.setTitle("发货人ID");
		this.f_consignor = field = this.table.newField(FN_consignor, TypeFactory.NVARCHAR(30));
		field.setTitle("发货人");
		this.f_consignedDate = field = this.table.newField(FN_consignedDate, TypeFactory.DATE);
		field.setTitle("发货日期");
		this.f_deliverPersonId = field = this.table.newField(FN_deliverPersonId, TypeFactory.GUID);
		field.setTitle("配送人Id");
		this.f_deliverPerson = field = this.table.newField(FN_deliverPerson, TypeFactory.NVARCHAR(30));
		field.setTitle("配送人");
		this.f_deliverDate = field = this.table.newField(FN_deliverDate, TypeFactory.DATE);
		field.setTitle("配送日期");
		this.f_arrivedConfirmId = field = this.table.newField(FN_arrivedConfirmId, TypeFactory.GUID);
		field.setTitle("确认到货人Id");
		this.f_arrivedConfirm = field = this.table.newField(FN_arrivedConfirm, TypeFactory.NVARCHAR(30));
		field.setTitle("确认到货人");
		this.f_arrivedConfirmDate = field = this.table.newField(FN_arrivedConfirmDate, TypeFactory.DATE);
		field.setTitle("确认到货日期");
		this.f_verificationCode = field = this.table.newField(FN_verificationCode, TypeFactory.NVARCHAR(100));
		field.setTitle("验证码");
		this.f_noVerificationReason = field = this.table.newField(FN_noVerificationReason, TypeFactory.NVARCHAR(1000));
		field.setTitle("跳过验证原因");
		this.f_returnFlag = field = this.table.newField(FN_returnFlag, TypeFactory.BOOLEAN);
		field.setTitle("是否有退货");
		field.setDefault(ConstExpression.builder.expOf(false));
		this.f_toDoor = field = this.table.newField(FN_toDoor, TypeFactory.BOOLEAN);
		field.setTitle("是否送货上门");
		field.setDefault(ConstExpression.builder.expOf(false));
		this.f_deliveryCost = field = this.table.newField(FN_deliveryCost, TypeFactory.NUMERIC(17,2));
		field.setTitle("运费");
		field.setDefault(ConstExpression.builder.expOf(0.0));
		this.f_bagsCost = field = this.table.newField(FN_bagsCost, TypeFactory.NUMERIC(17,2));
		field.setTitle("购物袋费用");
		field.setDefault(ConstExpression.builder.expOf(0.0));
		this.f_vantages = field = this.table.newField(FN_vantages, TypeFactory.NUMERIC(17,0));
		field.setTitle("送积分");
		field.setDefault(ConstExpression.builder.expOf(0.0));
		this.f_vantagesCost = field = this.table.newField(FN_vantagesCost, TypeFactory.NUMERIC(17,0));
		field.setTitle("消耗积分");
		field.setDefault(ConstExpression.builder.expOf(0.0));
		this.f_payType = field = this.table.newField(FN_payType, TypeFactory.CHAR(2));
		field.setTitle("支付类型（余额支付，在线支付）");
		this.f_lockedDeliveryBalance = field = this.table.newField(FN_lockedDeliveryBalance, TypeFactory.NUMERIC(17,0));
		field.setTitle("锁定上门送货包月次数");
		field.setDefault(ConstExpression.builder.expOf(0.0));
	}

}
