package com.spark.psi.order.purchase;

import com.jiuqi.dna.core.ObjectQuerier;
import com.jiuqi.dna.core.def.arg.ArgumentDefine;
import com.jiuqi.dna.core.def.query.QueryColumnDefine;
import com.jiuqi.dna.core.def.query.ORMDeclarator;

public class ORM_BuyOrderByOne extends ORMDeclarator<com.spark.order.purchase.intf.entity.PurchaseOrderInfo> {

	public final ArgumentDefine arg_tenants;

	public final QueryColumnDefine c_address;
	public final QueryColumnDefine c_consignee;
	public final QueryColumnDefine c_consigneeGuid;
	public final QueryColumnDefine c_consigneeTel;
	public final QueryColumnDefine c_disAmount;
	public final QueryColumnDefine c_relevaGuid;
	public final QueryColumnDefine c_relevaName;
	public final QueryColumnDefine c_Examin;
	public final QueryColumnDefine c_status;
	public final QueryColumnDefine c_Type;
	public final QueryColumnDefine c_billsNo;
	public final QueryColumnDefine c_createDate;
	public final QueryColumnDefine c_createGuid;
	public final QueryColumnDefine c_createPerson;
	public final QueryColumnDefine c_cuspFax;
	public final QueryColumnDefine c_cuspFullName;
	public final QueryColumnDefine c_cuspFullNamePY;
	public final QueryColumnDefine c_cuspGuid;
	public final QueryColumnDefine c_cuspName;
	public final QueryColumnDefine c_defEight;
	public final QueryColumnDefine c_defFive;
	public final QueryColumnDefine c_defFour;
	public final QueryColumnDefine c_defNine;
	public final QueryColumnDefine c_defOne;
	public final QueryColumnDefine c_defSeven;
	public final QueryColumnDefine c_defSix;
	public final QueryColumnDefine c_defTen;
	public final QueryColumnDefine c_defThree;
	public final QueryColumnDefine c_defTwo;
	public final QueryColumnDefine c_deptGuid;
	public final QueryColumnDefine c_goodsOkCount;
	public final QueryColumnDefine c_goodsTotalCount;
	public final QueryColumnDefine c_isStoped;
	public final QueryColumnDefine c_linkman;
	public final QueryColumnDefine c_linkmanGuid;
	public final QueryColumnDefine c_linkmanTel;
	public final QueryColumnDefine c_payDate;
	public final QueryColumnDefine c_rebutCause;
	public final QueryColumnDefine c_recid;
	public final QueryColumnDefine c_remark;
	public final QueryColumnDefine c_stopCause;
	public final QueryColumnDefine c_tenantsGuid;
	public final QueryColumnDefine c_saleGuid;
	public final QueryColumnDefine c_saleGuidB;
	public final QueryColumnDefine c_tenantsGuidB;
	public final QueryColumnDefine c_okDate;
	public final QueryColumnDefine c_totalAmount;

	public ORM_BuyOrderByOne() {
		this.arg_tenants = this.orm.getArguments().get(0);
		this.c_address = this.orm.getColumns().get(0);
		this.c_consignee = this.orm.getColumns().get(1);
		this.c_consigneeGuid = this.orm.getColumns().get(2);
		this.c_consigneeTel = this.orm.getColumns().get(3);
		this.c_disAmount = this.orm.getColumns().get(4);
		this.c_relevaGuid = this.orm.getColumns().get(5);
		this.c_relevaName = this.orm.getColumns().get(6);
		this.c_Examin = this.orm.getColumns().get(7);
		this.c_status = this.orm.getColumns().get(8);
		this.c_Type = this.orm.getColumns().get(9);
		this.c_billsNo = this.orm.getColumns().get(10);
		this.c_createDate = this.orm.getColumns().get(11);
		this.c_createGuid = this.orm.getColumns().get(12);
		this.c_createPerson = this.orm.getColumns().get(13);
		this.c_cuspFax = this.orm.getColumns().get(14);
		this.c_cuspFullName = this.orm.getColumns().get(15);
		this.c_cuspFullNamePY = this.orm.getColumns().get(16);
		this.c_cuspGuid = this.orm.getColumns().get(17);
		this.c_cuspName = this.orm.getColumns().get(18);
		this.c_defEight = this.orm.getColumns().get(19);
		this.c_defFive = this.orm.getColumns().get(20);
		this.c_defFour = this.orm.getColumns().get(21);
		this.c_defNine = this.orm.getColumns().get(22);
		this.c_defOne = this.orm.getColumns().get(23);
		this.c_defSeven = this.orm.getColumns().get(24);
		this.c_defSix = this.orm.getColumns().get(25);
		this.c_defTen = this.orm.getColumns().get(26);
		this.c_defThree = this.orm.getColumns().get(27);
		this.c_defTwo = this.orm.getColumns().get(28);
		this.c_deptGuid = this.orm.getColumns().get(29);
		this.c_goodsOkCount = this.orm.getColumns().get(30);
		this.c_goodsTotalCount = this.orm.getColumns().get(31);
		this.c_isStoped = this.orm.getColumns().get(32);
		this.c_linkman = this.orm.getColumns().get(33);
		this.c_linkmanGuid = this.orm.getColumns().get(34);
		this.c_linkmanTel = this.orm.getColumns().get(35);
		this.c_payDate = this.orm.getColumns().get(36);
		this.c_rebutCause = this.orm.getColumns().get(37);
		this.c_recid = this.orm.getColumns().get(38);
		this.c_remark = this.orm.getColumns().get(39);
		this.c_stopCause = this.orm.getColumns().get(40);
		this.c_tenantsGuid = this.orm.getColumns().get(41);
		this.c_saleGuid = this.orm.getColumns().get(42);
		this.c_saleGuidB = this.orm.getColumns().get(43);
		this.c_tenantsGuidB = this.orm.getColumns().get(44);
		this.c_okDate = this.orm.getColumns().get(45);
		this.c_totalAmount = this.orm.getColumns().get(46);
	}
}
