package com.spark.psi.storage.base.goods;

import com.jiuqi.dna.core.def.table.TableDeclarator;
import com.jiuqi.dna.core.type.TypeFactory;
import com.jiuqi.dna.core.def.table.TableFieldDefine;
import com.jiuqi.dna.core.def.table.TableFieldDeclare;

public final class TB_PSI_Base_GoodsItem extends TableDeclarator {

	public static final String TABLE_NAME ="PSI_Base_GoodsItem";

	public final TableFieldDefine f_goodsCode;
	public final TableFieldDefine f_goodsNo;
	public final TableFieldDefine f_goodsName;
	public final TableFieldDefine f_namePY;
	public final TableFieldDefine f_categoryId;
	public final TableFieldDefine f_spec;
	public final TableFieldDefine f_scale;
	public final TableFieldDefine f_needProduce;
	public final TableFieldDefine f_inventoryStrategy;
	public final TableFieldDefine f_goodsUnit;
	public final TableFieldDefine f_avgCost;
	public final TableFieldDefine f_standardCost;
	public final TableFieldDefine f_assessCost;
	public final TableFieldDefine f_shelfLife;
	public final TableFieldDefine f_warningDay;
	public final TableFieldDefine f_salePrice;
	public final TableFieldDefine f_originalPrice;
	public final TableFieldDefine f_lossRate;
	public final TableFieldDefine f_status;
	public final TableFieldDefine f_canDelete;
	public final TableFieldDefine f_refFlag;
	public final TableFieldDefine f_createDate;
	public final TableFieldDefine f_lastModifyDate;
	public final TableFieldDefine f_lastModifyPerson;
	public final TableFieldDefine f_goodsProperties;
	public final TableFieldDefine f_bomId;
	public final TableFieldDefine f_creatorId;
	public final TableFieldDefine f_creator;
	public final TableFieldDefine f_goodsId;
	public final TableFieldDefine f_serialNumber;

	public static final String FN_goodsCode ="goodsCode";
	public static final String FN_goodsNo ="goodsNo";
	public static final String FN_goodsName ="goodsName";
	public static final String FN_namePY ="namePY";
	public static final String FN_categoryId ="categoryId";
	public static final String FN_spec ="spec";
	public static final String FN_scale ="scale";
	public static final String FN_needProduce ="needProduce";
	public static final String FN_inventoryStrategy ="inventoryStrategy";
	public static final String FN_goodsUnit ="goodsUnit";
	public static final String FN_avgCost ="avgCost";
	public static final String FN_standardCost ="standardCost";
	public static final String FN_assessCost ="assessCost";
	public static final String FN_shelfLife ="shelfLife";
	public static final String FN_warningDay ="warningDay";
	public static final String FN_salePrice ="salePrice";
	public static final String FN_originalPrice ="originalPrice";
	public static final String FN_lossRate ="lossRate";
	public static final String FN_status ="status";
	public static final String FN_canDelete ="canDelete";
	public static final String FN_refFlag ="refFlag";
	public static final String FN_createDate ="createDate";
	public static final String FN_lastModifyDate ="lastModifyDate";
	public static final String FN_lastModifyPerson ="lastModifyPerson";
	public static final String FN_goodsProperties ="goodsProperties";
	public static final String FN_bomId ="bomId";
	public static final String FN_creatorId ="creatorId";
	public static final String FN_creator ="creator";
	public static final String FN_goodsId ="goodsId";
	public static final String FN_serialNumber ="serialNumber";

	//不可调用该构造方法.当前类只能由框架实例化.
	private TB_PSI_Base_GoodsItem() {
		super(TABLE_NAME);
		this.table.setTitle("商品条目");
		this.table.setCategory("基础数据主体");
		TableFieldDeclare field;
		this.f_goodsCode = field = this.table.newField(FN_goodsCode, TypeFactory.NVARCHAR(30));
		field.setTitle("商品条目编码");
		this.f_goodsNo = field = this.table.newField(FN_goodsNo, TypeFactory.NVARCHAR(30));
		field.setTitle("商品条目条码");
		this.f_goodsName = field = this.table.newField(FN_goodsName, TypeFactory.NVARCHAR(100));
		field.setTitle("商品条目名称");
		this.f_namePY = field = this.table.newField(FN_namePY, TypeFactory.NVARCHAR(30));
		field.setTitle("名称拼音");
		this.f_categoryId = field = this.table.newField(FN_categoryId, TypeFactory.GUID);
		field.setTitle("商品分类GUID");
		this.f_spec = field = this.table.newField(FN_spec, TypeFactory.NVARCHAR(100));
		field.setTitle("规格");
		this.f_scale = field = this.table.newField(FN_scale, TypeFactory.INT);
		field.setTitle("精度");
		this.f_needProduce = field = this.table.newField(FN_needProduce, TypeFactory.BOOLEAN);
		field.setTitle("是否需要生产");
		this.f_inventoryStrategy = field = this.table.newField(FN_inventoryStrategy, TypeFactory.CHAR(2));
		field.setTitle("库存策略");
		this.f_goodsUnit = field = this.table.newField(FN_goodsUnit, TypeFactory.NVARCHAR(5));
		field.setTitle("商品单位");
		this.f_avgCost = field = this.table.newField(FN_avgCost, TypeFactory.NUMERIC(17,2));
		field.setTitle("实际成本");
		this.f_standardCost = field = this.table.newField(FN_standardCost, TypeFactory.NUMERIC(17,2));
		field.setTitle("标准成本");
		this.f_assessCost = field = this.table.newField(FN_assessCost, TypeFactory.NUMERIC(17,2));
		field.setTitle("考核成本");
		this.f_shelfLife = field = this.table.newField(FN_shelfLife, TypeFactory.INT);
		field.setTitle("保质期");
		this.f_warningDay = field = this.table.newField(FN_warningDay, TypeFactory.INT);
		field.setTitle("预警天数");
		this.f_salePrice = field = this.table.newField(FN_salePrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("销售价格");
		this.f_originalPrice = field = this.table.newField(FN_originalPrice, TypeFactory.NUMERIC(17,2));
		field.setTitle("原价");
		this.f_lossRate = field = this.table.newField(FN_lossRate, TypeFactory.NUMERIC(17,4));
		field.setTitle("损耗率");
		this.f_status = field = this.table.newField(FN_status, TypeFactory.CHAR(2));
		field.setTitle("商品状态");
		this.f_canDelete = field = this.table.newField(FN_canDelete, TypeFactory.BOOLEAN);
		field.setTitle("是否可以删除");
		this.f_refFlag = field = this.table.newField(FN_refFlag, TypeFactory.BOOLEAN);
		field.setTitle("关联标识");
		this.f_createDate = field = this.table.newField(FN_createDate, TypeFactory.DATE);
		field.setTitle("数据插入时间");
		this.f_lastModifyDate = field = this.table.newField(FN_lastModifyDate, TypeFactory.DATE);
		field.setTitle("数据最后修改时间");
		this.f_lastModifyPerson = field = this.table.newField(FN_lastModifyPerson, TypeFactory.NVARCHAR(10));
		field.setTitle("数据最后修改人");
		this.f_goodsProperties = field = this.table.newField(FN_goodsProperties, TypeFactory.TEXT);
		field.setTitle("分类属性值");
		this.f_bomId = field = this.table.newField(FN_bomId, TypeFactory.GUID);
		field.setTitle("bom标志");
		this.f_creatorId = field = this.table.newField(FN_creatorId, TypeFactory.GUID);
		field.setTitle("创建人Guid");
		this.f_creator = field = this.table.newField(FN_creator, TypeFactory.NVARCHAR(30));
		field.setTitle("创建人");
		this.f_goodsId = field = this.table.newField(FN_goodsId, TypeFactory.GUID);
		field.setTitle("商品id");
		this.f_serialNumber = field = this.table.newField(FN_serialNumber, TypeFactory.NVARCHAR(30));
		field.setTitle("序号");
	}

}
